## **General**
1- What's the difference between a Machine Learning (ML) Model and a Machine Learning algorithm.

2- Why we need to study Linear Algebra for ML?

# Responses:
1- mechine learning model is the think we try to build,machine learning algorithms is the algorithms we use to build our model

2- we study leaning algebra becouse we work with complex structure (ex:imeges) ,we can store it only in vectors,matrixs and tensors and to work those we need learn algebre

**## Vectors:**

**1- create a vector: **

Our vector can be written as v=(2,1), but more formally we would use the following notation, in which the dimensional coordinate values for the vector are shown as a matrix:$$\vec{v} = \begin{bmatrix}2 \\ 1 \end{bmatrix}$$

In [1]:
import numpy as np
#TO DO...

v=np.array([[2],[1]])
print(v)

[[2]
 [1]]


### **2-Calculating Magnitude**

In [6]:
import math
#TO DO... 
m=math.sqrt(np.dot(v.T,v))
print(m)

2.23606797749979
2.23606797749979



**3- Vector Addition:**
So far, we've worked with one vector at a time. What happens when you need to add two vectors.

Let's take a look at an example, we already have a vector named v, as defined here:$$\vec{v} = \begin{bmatrix}2 \\ 1 \end{bmatrix}$$Now let's create a second vector, and called s like this:$$\vec{s} = \begin{bmatrix}-3 \\ 2 \end{bmatrix}$$

And we have :$$\vec{z} = \vec{v}+\vec{s}$$

In [7]:

import math
import numpy as np

v = [[2],[1]]
s = [[-3],[2]]
z =np.add(v,s)
print (z)

[[-1]
 [ 3]]



4- Dot Product Multiplication


$$ \vec{d}=\vec{v} \cdot \vec{s} = (v_{1} \cdot s_{1}) + (v_{2} \cdot s_{2}) ... + \; (v_{n} \cdot s_{n})$$

In [9]:

import math
import numpy as np

v = np.array([[2],[1]])
s = np.array([[-3],[2]])
d = np.dot(v.T,s)
print (d)

[[-4]]


## **Matrices:**

# 1- create a Matrice:
A matrix arranges numbers into rows and columns, like this:

$$A = \begin{bmatrix}
  1 &amp; 2 &amp; 3 \\
  4 &amp; 5 &amp; 6
 \end{bmatrix}
$$

In [12]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
print (A)

[[1 2 3]
 [4 5 6]]



#2- Matrix Transposition
You can transpose a matrix, that is switch the orientation of its rows and columns. You indicate this with a superscript T, like this:

$$\begin{bmatrix}1 &amp; 2 &amp; 3 \\4 &amp; 5 &amp; 6\end{bmatrix}^{T} = \begin{bmatrix}1 &amp; 42 &amp; 53 &amp; 6 \end{bmatrix}$$

a- How can we do it mathematically? 

Aij:=Aji



b- with Python: 

In [13]:
import numpy as np

A=A.T
print(A)

[[1 4]
 [2 5]
 [3 6]]


## **Eigendecomposition:**

So we've learned a little about eigenvalues and eigenvectors; but you may be wondering what use they are. Well, one use for them is to help decompose transformation matrices.

1- How can we decompose a matrix? ( Rules and steps)
2- (Bonus) Do it in python with your exampls.

1-compute the eigenvectors

2-AP=PD   A=PDP-1
find P

In [ ]:
#2 bonus
import numpy as np
eigenVectors=np.linalg.eig(A)

In [ ]:
fork the repo to my github

git clone https://github.com/amir15bfk/Test-01

solve the test

git add Test-01

git commit -m "test"

git push
